### ISSUE TITLE
Pull from f16

### ISSUE THREAD

**Issue by mterwill** [c4cs/assignments#13]
Not sure this is up to date; would like to xref with `c4cs/c4cs.github.io` repo.

**Comment by ppannuto** [comment]
I abandoned this repo last term and just used the site repo as the canonical source. The original motivation for the split repo was that anything in the site was auto-published, but when I refactored to use jekyll and added support for time-releasing assignments, I don't think there's much of a reason for a separate repo any more.

**Comment by mterwill** [comment]
@the-alex I think you were in favor of this repo? Makes no difference to me, seems to make life easier to keep it all in one place.

**Comment by the-alex** [comment]
I'm okay keeping it in one place moving forward. I can't think of a really compelling argument for keeping them split when we're already used to keeping them in one spot now. \shrug
